### ISSUE TITLE
How Dropbox secures your password (and a side conversation about Password managers)

### ISSUE THREAD

**Issue by ei8fdb** [ownpass/ownpass#18]
I came across this interesting thread on HackerNews:

https://news.ycombinator.com/item?id=12548210

links to a Dropbox blogpost: https://blogs.dropbox.com/tech/2016/09/how-dropbox-securely-stores-your-passwords/

The discussion on password managers was interesting too.

**Comment by waltertamboer** [comment]
Thanks for the info, I've posted it on [Gitter](https://gitter.im/ownpass/Lobby)
